FROM node:21.1.0-alpine3.18

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && \
    pnpm config set auto-install-peers true && \
    apk add --no-cache su-exec=0.2-r3

WORKDIR /usr/src/app

COPY --chown=node:node package.json pnpm-lock.yaml ./

RUN chown -R node:node /usr/src/app && \
    # clear volume and drop privileges on start
    sed -i "s@^exec@rm -rf ./node_modules/* ./node_modules/.bin; chown node:node ./node_modules\nexec su-exec node @g" /usr/local/bin/docker-entrypoint.sh && \
    # install node_modules and move them to /. `npm run docker-dev` will copy
    # them into the working directory on startup
    # (see https://stackoverflow.com/a/43350779)
    su node -c 'pnpm install --frozen-lockfile' && mv ./node_modules /

# dev http
EXPOSE 3000
CMD [ "npm", "run", "docker-dev" ]
