FROM golang:1.18.5-alpine3.15

# set default timezone
ARG TZ=Europe/Berlin
ENV DEFAULT_TZ ${TZ}
ENV CGO_ENABLED=1

WORKDIR /app

# add pg_dump for db migrations and timezone for logs
RUN apk add --no-cache \
    gcc=10.3.1_git20211027-r0 \
    musl-dev=1.2.2-r7 \
    postgresql13-client=13.8-r0 \
    tzdata=2022c-r0 && \
    ln -snf /usr/share/zoneinfo/${DEFAULT_TZ} /etc/localtime && \
    # Go Watch: https://github.com/mitranim/gow
    go install github.com/mitranim/gow@v0.0.0-20220125090630-5348a1592279 && \
    # Soda CLI: https://gobuffalo.io/en/docs/db/toolbox/
    go install github.com/gobuffalo/pop/v6/soda@v6.0.3

# cache go deps
COPY go.mod go.sum ./
RUN go mod download

VOLUME /app
EXPOSE 8080
CMD ["gow", "run", "-race", "./cmd/api", "--dev", "--log", "debug"]
