services:
    nginx:
        image: nginxinc/nginx-unprivileged:1.21.6-alpine
        ports:
            - "5000:8080"
        hostname: rueder
        networks:
            - http_default
            - default
        volumes:
            - type: bind
              source: ./config/nginx-conf.d-test
              target: /etc/nginx/conf.d
        depends_on:
            - frontend
            - api
            - auth

    frontend:
        build:
            context: ./frontend
            args:
                # always add the trailing slash!
                VITE_BASE_URL: "/rueder/"
                VITE_RUEDER_BASE_URL_LOGIN: "/rueder/"
                VITE_RUEDER_BASE_URL_API: "/rueder/api/v1/"
                VITE_RUEDER_BASE_URL_IMAGEPROXY: "/rueder/imageproxy/"
        image: rueder3-frontend-testprod
        networks:
            - default

    api:
        build:
            context: ./backend
            dockerfile: ./docker/api/Dockerfile
        image: rueder3-api-testprod
        env_file:
            - ./config/rueder-test.env
        depends_on:
            - db
            - auth
        networks:
            - default
            - db

    worker:
        build:
            context: ./backend
            dockerfile: ./docker/worker/Dockerfile
        image: rueder3-worker-testprod
        env_file:
            - ./config/rueder-test.env
        depends_on:
            - db
        networks:
            - db

    db:
        image: postgres:13.6-alpine
        environment:
            # this must be the same as in ./backend/config/database.yml.
            # if you want to override it you should bind mount to /app/database.yml instead of changing it there!
            POSTGRES_DB: rueder_production
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - type: volume
              source: db
              target: /var/lib/postgresql/data
        networks:
            - db

    auth:
        image: tarent/loginsrv:1.3.0
        env_file:
            - ./config/rueder-test.env
        depends_on:
            - authbackend
        networks:
            - default
            - authbackend

    authbackend:
        build:
            context: ./backend
            dockerfile: ./docker/authbackend/Dockerfile
        image: rueder3-authbackend-testprod
        env_file:
            - ./config/rueder-test.env
        depends_on:
            - db
        networks:
            - authbackend
            - db

    imgproxy:
        image: darthsim/imgproxy:v3.5.0
        env_file:
            - ./config/imgproxy.env
        volumes:
            - type: bind
              source: ./frontend/public/dummy.png
              target: /dummy.png
              read_only: true


volumes:
    db:

networks:
    default:
    db:
    authbackend:
    http_default:
        external: true
