services:
    dev:
        build:
            context: .
            dockerfile: ./docker/dev/Dockerfile
        image: rueder3-dev
        env_file:
            - ./rueder-dev.env
        ports:
            - "127.0.0.1:8080:8080" # api
            - "127.0.0.1:8081:8080" # ff
            - "127.0.0.1:8083:8080" # events
        volumes:
            - ./:/app/
        depends_on:
            - db

    db:
        image: docker.io/library/postgres:13.6-alpine
        environment:
            POSTGRES_DB: rueder_development
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - rueder_dev_db:/var/lib/postgresql/data

    auth:
        # use the official image if you don't need CORS in your dev environment
        # image: tarent/loginsrv
        # use my branch of loginsrv if you need CORS: https://github.com/spezifisch/loginsrv/tree/cors
        # (build and tag the docker image using `docker build -t custom-tarent-loginsrv .` in the loginsrv repository)
        image: custom-tarent-loginsrv
        env_file:
            - ./rueder-dev.env
        ports:
            - "127.0.0.1:8082:8080"
        depends_on:
          - dev

    rabbitmq:
        image: rabbitmq:3.12.2-management
        container_name: "rabbitmq"
        ports:
            - "127.0.0.1:5672:5672"
            - "127.0.0.1:15672:15672"
        volumes:
            - ./config/rabbitmq-logging-dev.conf:/etc/rabbitmq/conf.d/20-logging.conf
            - rueder_dev_rabbitmq_data:/var/lib/rabbitmq

volumes:
    rueder_dev_db:
    rueder_dev_rabbitmq_data:
