FROM golang:1.18.1-alpine3.15

# set default timezone
ARG TZ=Europe/Berlin
ENV DEFAULT_TZ ${TZ}
ENV CGO_ENABLED=1

WORKDIR /app

# add timezone for logs
RUN apk add --no-cache\
    gcc=10.3.1_git20211027-r0 \
    musl-dev=1.2.2-r7 \
    tzdata=2022a-r0 && \
    ln -snf /usr/share/zoneinfo/${DEFAULT_TZ} /etc/localtime && \
    # Go Watch: https://github.com/mitranim/gow
    go install github.com/mitranim/gow@v0.0.0-20220125090630-5348a1592279 && \
    # install swag
    go install github.com/swaggo/swag/cmd/swag@v1.8.1

# copy runner that generates swag docs and starts gow
COPY docker/feedfinder/run-feedfinder-dev.sh /

# cache go deps
COPY go.mod go.sum ./
RUN go mod download

VOLUME /app
# we use a separate volume for the docs so they don't clash with api's docs
# which are in the docs dir on the host
VOLUME /app/docs
EXPOSE 8080
CMD ["/run-feedfinder-dev.sh"]
