name: backend lint and tests

on:
    push:
        branches: [main]
    pull_request:

    workflow_dispatch:

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.18

            - name: Run linter
              run: cd backend && make lint

            - name: Run tests
              run: cd backend && make test
