name: frontend tests

on:
    push:
        branches: [main]
    pull_request:

    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./frontend

        steps:
            - uses: actions/checkout@v3

            - name: Install modules
              run: npm ci --no-audit

            - name: Run tests
              run: npm run test
