name: frontend tests

on:
    push:
        branches: [main]
    pull_request:

    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: [16, 18]

        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2.2.2
              with:
                  version: 7

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: "./frontend/pnpm-lock.yaml"

            - name: Install modules
              working-directory: ./frontend
              run: pnpm ci --no-audit

            - name: Run tests
              working-directory: ./frontend
              run: pnpm run test
