name: frontend lint/validate

on:
    push:
        branches: [main]
    pull_request:

    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: [16, 18]

        defaults:
            run:
                working-directory: ./frontend

        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2.2.2
              with:
                  version: 7

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
                  cache-dependency-path: "**/pnpm-lock.json"

            - name: Install modules
              run: pnpm ci --no-audit

            - name: Run linters
              run: pnpm lint

            - name: Run svelte-checks
              run: pnpm validate
