name: frontend lint/validate

on:
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v3

      - name: Install modules
        run: npm ci --no-audit

      - name: Run linters
        run: npm run lint

      - name: Run svelte-checks
        run: npm run validate
