name: frontend snyk hook

on:
    push:
        branches: [main]
    pull_request:

jobs:
    pnpm_snyk_check:
        runs-on: ubuntu-latest
        name: Snyk post processing
        steps:
            - uses: actions/checkout@v2

            - name: Snyk API pnpm scan
              id: pnpm-scan-api-tool
              uses: snyk-tech-services/snyk-pnpm-github-action@master
              with:
                  snykToken: ${{ secrets.snykToken }}
                  pnpmLockfilePath: "./frontend"
                  snykOrganization: "spezifisch"
                  IncludeDev: "false"

